In [1]:
import numpy as np
from dezero import Variable
import dezero.functions as F

In [2]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
y = F.get_item(x, 1)
print(y)

variable([4 5 6])


In [3]:
y.backward()
print(x.grad)

variable([[0 0 0]
          [1 1 1]])


In [4]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
indices = np.array([0, 0, 1])
y = F.get_item(x, indices)
print(y)

variable([[1 2 3]
          [1 2 3]
          [4 5 6]])


In [6]:
Variable.__getitem__ = F.get_item

y = x[1]
print(y)

y = x[:,2]
print(y)

variable([4 5 6])
variable([3 6])


In [7]:
if '__file__' in globals():
    import os, sys
    sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
import numpy as np
np.random.seed(0)
from dezero import Variable, as_variable
import dezero.functions as F
from dezero.models import MLP


def softmax1d(x):
    x = as_variable(x)
    y = F.exp(x)
    sum_y = F.sum(y)
    return y / sum_y


model = MLP((10, 3))

x = Variable(np.array([[0.2, -0.4]]))
y = model(x)
p = softmax1d(y)
print(y)
print(p)

x = np.array([[0.2, -0.4], [0.3, 0.5], [1.3, -3.2], [2.1, 0.3]])
t = np.array([2, 0, 1, 0])

y = model(x)
p = F.softmax_simple(y)
print(y)
print(p)

loss = F.softmax_cross_entropy_simple(y, t)
loss.backward()
print(loss)

variable([[-0.61505778 -0.42790161  0.31733289]])
variable([[0.21068639 0.25404893 0.53526469]])
variable([[-0.61505778 -0.42790161  0.31733289]
          [-0.76395313 -0.2497645   0.18591382]
          [-0.52006391 -0.96254612  0.57818938]
          [-0.94252164 -0.50307479  0.17576323]])
variable([[0.21068639 0.25404893 0.53526469]
          [0.19019916 0.31806646 0.49173438]
          [0.21545395 0.13841619 0.64612986]
          [0.17820704 0.27655034 0.54524263]])
variable(1.4967442524053063)
