In [7]:
import numpy as np
from dezero import Variable
import dezero.functions as F

In [8]:
x = np.array([1, 2, 3])
y = np.broadcast_to(x, (2, 3))
print(y)

[[1 2 3]
 [1 2 3]]


In [9]:
from dezero.utils import sum_to

In [10]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = sum_to(x, (1, 3))
print(y)

y = sum_to(x, (2, 1))
print(y)

[[5 7 9]]
[[ 6]
 [15]]


In [11]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
y = Variable(np.array([10]))
print(x+y)

variable([[11 12 13]
          [14 15 16]])


In [12]:
x0 = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
x1 = Variable(np.array([10]))
y = x0 + x1
print(y)

y.backward()
print(x0.grad)
print(x1.grad)

variable([[11 12 13]
          [14 15 16]])
variable([[1 1 1]
          [1 1 1]])
variable([6])


In [13]:
x0 = Variable(np.array([1, 2, 3]))
x1 = Variable(np.array([10]))
y = x0 + x1
print(y)

y.backward()
print(x0.grad)
print(x1.grad)

variable([11 12 13])
variable([1 1 1])
variable([3])
