In [1]:
import numpy as np
from dezero import Variable
import dezero.functions as F

In [2]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
y = F.reshape(x, (6,))
y.backward(retain_grad=True)
print(x.grad)

variable([[1 1 1]
          [1 1 1]])


In [3]:
x = Variable(np.random.randn(1, 2, 3))
y = x.reshape((2, 3)) # Tuple
y = x.reshape(2, 3)

In [4]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
y = F.transpose(x)
y.backward()
print(x.grad)

variable([[1 1 1]
          [1 1 1]])


In [5]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
y = F.transpose(x)
y.backward(retain_grad=True)
print(x.grad)
print(y.grad)

variable([[1 1 1]
          [1 1 1]])
variable([[1 1]
          [1 1]
          [1 1]])


In [6]:
x = Variable(np.random.rand(2, 3))
y = x.transpose()
y = x.T
print(y)

variable([[0.09110637 0.04687123]
          [0.66891918 0.43934143]
          [0.3886024  0.66059517]])
